apiVersion: v1
kind: Template
metadata:
  name: has-builder
  annotations:
    description: HAS components build template
    tags: networking,storage

parameters:
  - name: ID
    value: "hdfs"
    description: Component ID to tag openshift elements
    required: true
  - name: REPOSITORY
    value: "https://github.com/BBVA/docker-hdfs-alluxio-spark.git"
    description: Source code respository
    required: true
  - name: CONTEXTDIR
    value: "hdfs"
    description: Docker image path in repository
    required: true

objects:

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${ID}
      namespace: has
    spec: {}

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${ID}
      namespace: has
    spec:
      triggers:
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: >-
            ${REPOSITORY}
        contextDir: ${CONTEXTDIR}
      strategy:
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: ${ID}:latest
