apiVersion: v1
kind: BuildConfig
metadata:
  name: has-spark-submitter
  namespace: has
spec:
  triggers:
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: >-
        https://github.com/BBVA/docker-hdfs-alluxio-spark.git
    contextDir: spark-submitter
    sourceSecret:
      name: sshsecret
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'has-spark-submitter:latest'
