apiVersion: v1
kind: Template
metadata:
  name: zeppelin
  annotations:
    description: zeppelin cluster master
    tags: networking,storage

parameters:
  - name: ID
    value: "1Gi"
    description: Zeppelin client ID
    required: true
  - name: STORAGE
    value: "1Gi"
    description: Storage assigned to the node
    required: true
  - name: IMAGE
    value: "zeppelin"
    description: HAS szeppelinpark Docker image
    required: true

objects:

  - apiVersion: v1
    kind: Service
    metadata:
      name: zeppelin-${ID}
    spec:
      selector:
        app: "zeppelin"
      ports:
        - name: spark-ui
          protocol: TCP
          port: 4040
          targetPort: 4040
        - name: zeppelin-ui-websockets
          protocol: TCP
          port: 8081
          targetPort: 8081
        - name: zeppelin-ui
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: spark-driver-port
          protocol: TCP
          port: 51000
          targetPort: 51000
        - name: spark-fileserver-port
          protocol: TCP
          port: 51100
          targetPort: 51100
        - name: spark-broadcast-port
          protocol: TCP
          port: 51200
          targetPort: 51200
        - name: spark-replclassserver-port
          protocol: TCP
          port: 51300
          targetPort: 51300
        - name: spark-blockmanager-port
          protocol: TCP
          port: 51400
          targetPort: 51400
        - name: spark-executor-port
          protocol: TCP
          port: 51500
          targetPort: 51500

  - apiVersion: v1
    kind: Route
    metadata:
      name: zeppelin-dashboard
      namespace: has
    spec:
      to:
          kind: Service
          name: zeppelin-${ID}
          weight: 100
      port:
          targetPort: zeppelin-ui
      wildcardPolicy: None

  - apiVersion: v1
    kind: Route
    metadata:
      name: zeppelin-driver
      namespace: has
    spec:
      to:
          kind: Service
          name: zeppelin-${ID}
          weight: 100
      port:
          targetPort: spark-ui
      wildcardPolicy: None

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: zeppelin
      namespace: has
      labels:
        app: zeppelin
    spec:
      strategy:
        type: Recreate
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - zeppelin
            from:
              kind: ImageStreamTag
              namespace: has
              name: 'zeppelin:latest'
      replicas: 1
      test: false
      selector:
        app: zeppelin
        deploymentconfig: zeppelin
      template:
        metadata:
          labels:
            app: zeppelin
            deploymentconfig: zeppelin
            type: "aux"
          annotations:
            scheduler.alpha.kubernetes.io/affinity: >
                {
                  "podAntiAffinity": {
                    "preferredDuringSchedulingIgnoredDuringExecution": [{
                      "weight": 1,
                      "podAffinityTerm": {
                        "labelSelector": {
                          "matchExpressions": [{
                            "key": "type",
                            "operator": "In",
                            "values": ["worker", "master", "driver"]
                          }]
                        },
                        "topologyKey": "kubernetes.io/hostname"
                      }
                    }]
                  }
                }
        spec:
          volumes:
            - name: zeppelin-storage
              emptyDir: {}
          hostname: zeppelin-${ID}
          subdomain: has
          containers:
            - name: zeppelin
              image: ${IMAGE}
              resources: {}
              args:
                - master
                - start
              volumeMounts:
                - name: zeppelin-storage
                  mountPath: /data
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: Always
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 600
                timeoutSeconds: 10
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
