apiVersion: v1
kind: Template
metadata:
  name: hdfs-datanode
  annotations:
    description: HDFS cluster
    tags: networking,storage

parameters:
  - name: STORAGE
    value: "1Gi"
    description: Storage assigned to the node
    required: true
  - name: IMAGE
    value: "hdfs"
    description: HAS HDFS Docker image
    required: true

objects:

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: hdfs-datanode-storage
      namespace: has
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: ${STORAGE}
      volumeName: hdfs-datanode-storage


  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: hdfs-datanode
      namespace: has
      labels:
        app: hdfs-datanode
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - hdfs-datanode
            from:
              kind: ImageStreamTag
              namespace: has
              name: 'hdfs:latest'
      replicas: 1
      test: false
      selector:
        app: hdfs-datanode
        deploymentconfig: hdfs-datanode
      template:
        metadata:
          labels:
            app: hdfs-datanode
            deploymentconfig: hdfs-datanode
        spec:
          volumes:
            - name: hdfs-datanode-storage
              persistentVolumeClaim:
                claimName: hdfs-datanode-storage
          containers:
            - name: hdfs-datanode
              image: ${IMAGE}
              resources: {}
              environment:
                - cluster-name="hdfs-namenode"
              args:
                - datanode
                - start
                - hdfs-namenode
              volumeMounts:
                - name: hdfs-datanode-storage
                  mountPath: /data
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}

  - apiVersion: v1
    kind: Service
    metadata:
      name: hdfs-datanode
    spec:
      selector:
        app: "hdfs-datanode"
      ports:
        - name: dfs-datanode-address
          protocol: TCP
          port: 50010
          targetPort: 50010
        - name: dfs-datanode-http-address
          protocol: TCP
          port: 50075
          targetPort: 50075
        - name: dfs-datanode-ipc-address
          protocol: TCP
          port: 50020
          targetPort: 50020

  - apiVersion: v1
    kind: Route
    metadata:
      name: hdfs-datanode-dashboard
      namespace: has
      spec:
        to:
          kind: Service
          name: hdfs-datanode
          weight: 100
        port:
          targetPort: dfs-datanode-http-address
        wildcardPolicy: None

