apiVersion: v1
kind: Template
metadata:
  name: spark-master
  annotations:
    description: Sparm cluster master
    tags: networking,storage

parameters:
  - name: IMAGE
    value: "spark"
    description: HAS spark Docker image
    required: true
  - name: SPARK_MASTER_WEBUI_PORT
    required: true
  - name: SPARK_WORKER_MEMORY
    required: true
  - name: SPARK_WORKER_PORT
    required: true
  - name: SPARK_WORKER_WEBUI_PORT
    required: true
  - name: SPARK_DAEMON_MEMORY
    required: true


objects:
  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: "spark-master-storage"
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "5Gi"

  - apiVersion: v1
    kind: Service
    metadata:
      name: spark-master
    spec:
      selector:
        app: "spark-master"
      ports:
        - name: spark-master-service
          protocol: TCP
          port: 7077
          targetPort: 7077
        - name: spark-master-ui
          protocol: TCP
          port: 8080
          targetPort: 8080

  - apiVersion: v1
    kind: Route
    metadata:
      name: spark-master-dashboard
      namespace: has
    spec:
      to:
          kind: Service
          name: spark-master
          weight: 100
      port:
          targetPort: spark-master-ui
      wildcardPolicy: None

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: spark-master
      namespace: has
      labels:
        app: spark-master
    spec:
      strategy:
        type: Recreate
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - spark-master
            from:
              kind: ImageStreamTag
              namespace: has
              name: 'spark:latest'
      replicas: 1
      test: false
      selector:
        app: spark-master
        deploymentconfig: spark-master
      template:
        metadata:
          labels:
            app: spark-master
            deploymentconfig: spark-master
            type: "master"
          annotations:
            scheduler.alpha.kubernetes.io/affinity: >
                {
                  "podAffinity": {
                    "preferredDuringSchedulingIgnoredDuringExecution": [{
                      "weight": 1,
                      "podAffinityTerm": {
                        "labelSelector": {
                          "matchExpressions": [{
                            "key": "type",
                            "operator": "In",
                            "values": ["master"]
                          }]
                        },
                        "topologyKey": "kubernetes.io/hostname"
                      }
                    }]
                  },
                  "podAntiAffinity": {
                    "requiredDuringSchedulingIgnoredDuringExecution": [{
                        "labelSelector": {
                          "matchExpressions": [{
                            "key": "type",
                            "operator": "In",
                            "values": ["worker", "aux"]
                          }]
                        },
                      "topologyKey": "kubernetes.io/hostname"
                    }]
                  }
                }
        spec:
          hostname: spark-master
          volumes:
            - name: spark-master-storage
              persistentVolumeClaim:
                claimName: spark-master-storage
          containers:
            - name: spark-master
              image: ${IMAGE}
              resources: {}
              env:
                - name: SPARK_MASTER_WEBUI_PORT
                  value: "${SPARK_MASTER_WEBUI_PORT}"
                - name: SPARK_WORKER_MEMORY
                  value: "${SPARK_WORKER_MEMORY}"
                - name: SPARK_WORKER_PORT
                  value: "${SPARK_WORKER_PORT}"
                - name: SPARK_WORKER_WEBUI_PORT
                  value: "${SPARK_WORKER_WEBUI_PORT}"
                - name: SPARK_DAEMON_MEMORY
                  value: "${SPARK_DAEMON_MEMORY}"
              args:
                - master
                - start
                - spark-master
              volumeMounts:
                - name: spark-master-storage
                  mountPath: /data
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: Always
              livenessProbe:
                # an http probe
                httpGet:
                  path: /
                  port: 8080
                  initialDelaySeconds: 15
                  timeoutSeconds: 1
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
